Converting grabssh/fixssh setup to use $GRABSSH_DIR variable

diff --git a/ssh/grabssh b/ssh/grabssh
--- a/ssh/grabssh
+++ b/ssh/grabssh
@@ -1,14 +1,21 @@
 #!/bin/sh
 
 # ssh variables to yank
-SSHV="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"
+SSH_VARIABLES="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"
 
 # where to put the output script
-DESTDIR=$HOME/tmp
+GRABSSH_DIR="$GRABSSH_DIR"
+if [ -z "$GRABSSH_DIR" ]; then
+    echo "Error: \$GRABSSH_DIR is not set!" >&2
+    exit 1
+fi
 
 # grab each variable name and format it as an export statement
-for x in ${SSHV} ; do
-    (eval echo $x=\$$x) | sed  's/=/="/
-                                s/$/"/
-                                s/^/export /'
-done 1>$DESTDIR/fixssh
+for x in $SSH_VARIABLES; do
+    (eval echo $x=\$$x) |
+        sed -e '
+            s/=/="/
+            s/$/"/
+            s/^/export /
+        '
+done 1> $GRABSSH_DIR/fixssh
